apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: my_pubsub
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    value: ""
  - name: poolSize
    value: "1000"